# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 22.1.0
  hooks:
    - id: black

- repo: https://github.com/pycqa/isort
  rev: 5.10.1
  hooks:
    - id: isort

- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.931
  hooks:
    - id: mypy

- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 0.2.0
  hooks:
    - id: sync_with_poetry

- repo: local
  hooks:
    - id: gen_readme
      name: Generate README.md from help text
      language: system
      entry: bash -c 'slide-extractor -h > README.md'
      always_run: true
